server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:customdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: ssoadmin
      password: ssopass
    realmImportFile: sso-realm.json
